#!/usr/bin/env python3
"""
tools/gen_sw.py — writes sw.js, the offline service worker.

The app makes no network calls of its own, so the only thing standing between
it and a plane journey is that Safari has to fetch the page from GitHub Pages
each time it opens. A service worker removes that: after one online visit the
whole app — every MP3 included — lives on the device.

The asset list is generated rather than hand-written because it has to stay in
step with audio/, which gen_audio.py grows. VERSION is a content hash, so a
redeploy invalidates the old cache automatically and a child never gets a
half-updated app.

    python tools/gen_sw.py

Re-run it after gen_audio.py or any change to the shell.
"""

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "sw.js"

# The app itself. All of this must cache or the install fails — a missing
# lib/ file offline is a blank screen, which is worse than staying online.
SHELL_GLOBS = [
    "index.html", "styles.css", "app.js", "manifest.json",
    "icon-180.png", "icon-512.png",
    "lib/*.js", "games/*.js", "data/*.js", "data/lessons/*.js",
    "art/*.svg",
]

# Speech. Cached best-effort: one unreachable MP3 should not cost the child
# the whole offline app, and lib/audio.js already copes with a missing file.
AUDIO_GLOBS = ["audio/**/*.mp3"]


def collect(globs):
    out = []
    for g in globs:
        for p in sorted(ROOT.glob(g)):
            if p.is_file():
                out.append(p.relative_to(ROOT).as_posix())
    return out


# Text files are hashed with their line endings normalised. Git rewrites them
# to CRLF on checkout under core.autocrlf, so hashing raw bytes would make the
# version change on a fresh clone and report a perfectly good sw.js as stale.
TEXT_SUFFIXES = {".html", ".css", ".js", ".json", ".md"}


CRLF = bytes((13, 10))
LF = bytes((10,))


def content_for_hash(path):
    if path.suffix.lower() in TEXT_SUFFIXES:
        return path.read_bytes().replace(CRLF, LF)
    return path.read_bytes()


def version_of(files):
    """Content hash of the precache list. Also used by verify_data.py to catch
    an sw.js left stale after gen_audio.py added files."""
    h = hashlib.sha256()
    for rel in files:
        h.update(rel.encode("utf-8"))
        h.update(content_for_hash(ROOT / rel))
    return h.hexdigest()[:12]


def main():
    shell = collect(SHELL_GLOBS)
    audio = collect(AUDIO_GLOBS)

    missing = [f for f in ("index.html", "styles.css", "app.js") if f not in shell]
    if missing:
        print(f"shell is incomplete, missing {missing}", file=sys.stderr)
        return 1

    version = version_of(shell + audio)

    def js_list(items, indent="  "):
        return "\n".join(f"{indent}'{i}'," for i in items)

    js = f"""/*
 * sw.js — GENERATED by tools/gen_sw.py. Do not hand-edit; re-run that script.
 *
 * Makes 拼音岛 work with no internet at all. The app never talks to a network
 * by itself — no backend, no accounts, no CDN — so once these files are on the
 * device there is nothing left to fetch.
 *
 * VERSION is a hash of every cached file. Change any of them, re-run the
 * generator, redeploy, and the old cache is dropped on activate.
 */

const VERSION = '{version}';
const CACHE = 'pinyin-' + VERSION;

/* The app. Must all cache, or we would ship a blank screen offline. */
const SHELL = [
  './',
{js_list(shell)}
];

/* {len(audio)} MP3s. Best-effort — a single failure must not fail the install. */
const AUDIO = [
{js_list(audio)}
];

self.addEventListener('install', event => {{
  event.waitUntil((async () => {{
    const cache = await caches.open(CACHE);
    await cache.addAll(SHELL);
    for (let i = 0; i < AUDIO.length; i += 40) {{
      await Promise.allSettled(AUDIO.slice(i, i + 40).map(u => cache.add(u)));
    }}
    await self.skipWaiting();
  }})());
}});

self.addEventListener('activate', event => {{
  event.waitUntil((async () => {{
    const keys = await caches.keys();
    await Promise.all(
      keys.filter(k => k.startsWith('pinyin-') && k !== CACHE).map(k => caches.delete(k))
    );
    await self.clients.claim();
  }})());
}});

self.addEventListener('fetch', event => {{
  const req = event.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;

  /* Opening the app: cached shell wins the moment the network is gone. */
  if (req.mode === 'navigate') {{
    event.respondWith((async () => {{
      try {{
        return await fetch(req);
      }} catch (e) {{
        const fallback = await caches.match(new URL('index.html', self.registration.scope).href);
        return fallback || Response.error();
      }}
    }})());
    return;
  }}

  event.respondWith((async () => {{
    const hit = await caches.match(req, {{ ignoreSearch: true }});
    if (hit) return hit;
    try {{
      const res = await fetch(req);
      if (res.ok && res.type === 'basic') {{
        const cache = await caches.open(CACHE);
        cache.put(req, res.clone());
      }}
      return res;
    }} catch (e) {{
      /* Offline and never cached — audio/overrides/* is probed on purpose and
         is expected to miss, so answer like the server would rather than throw. */
      return new Response('', {{ status: 404, statusText: 'offline' }});
    }}
  }})());
}});
"""

    OUT.write_text(js, encoding="utf-8", newline="\n")
    size = sum((ROOT / f).stat().st_size for f in shell + audio)
    print(f"wrote sw.js  version={version}")
    print(f"  shell {len(shell)} files, audio {len(audio)} files, {size/1048576:.1f} MB total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
